### ISSUE TITLE
C# performance issue

### ISSUE THREAD

**Issue by elpechos** [matt77hias/cs-smallpt#1]
Hello, Would just like to mention that the c# version performs poorly because Vector3 is implemented as a class. More than 3/4 of the time is just spent constructing billions of Vector3 objects.

 If I refactor Vector3 to a struct I get a ~4-5X increase in performance

I also added multi-processor support, now the c# version beats the C++ version by a fair bit (make sure to build in release mode and x64) :)

[cs-smallpt-fast.zip](https://github.com/matt77hias/cs-smallpt/files/2739044/cs-smallpt-fast.zip)

**Comment by matt77hias** [comment]
Integrated both the `struct` optimization and a separate multi-threaded version. 

Thanks a lot for the contribution!
